// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxXXgTVZkXbM34cJlRyMLfXXJ3Q2dLgPQ',
    appId: '1:555611366952:android:c6673dd9db40c01be4f71d',
    messagingSenderId: '555611366952',
    projectId: 'feat-authentication',
    databaseURL: 'https://feat-authentication-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feat-authentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEbjuS4Yocc6jiiHF0FLuhefqpqDroYAc',
    appId: '1:555611366952:ios:e3d844032dffd266e4f71d',
    messagingSenderId: '555611366952',
    projectId: 'feat-authentication',
    databaseURL: 'https://feat-authentication-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feat-authentication.appspot.com',
    iosClientId: '555611366952-u5m74cse962cm801u2lk62vuhge3p7hi.apps.googleusercontent.com',
    iosBundleId: 'c',
  );
}
